### PR TITLE
Remove unused GCC flag and fix wfc include path

### PR DESCRIPTION
**Pull request by wdhg**

### CODE REVIEW

**Comment by Soneji** [comment]
Hi @wdhg 

This gcc flag is not unused, it is important on some systems to link the `<math.h>` library

https://github.com/noor-gate/quantum-music/blob/aba9fdc930ab03a1fbb7f82b36d2761e1007bf62/wfc/wfc.c#L3

**Comment by wdhg** [comment]
It causes this error on my system:

```
gcc -Wall -g -Werror -pedantic -lm -I/usr/local/opt/icu4c/include  -c -o filereader.o filereader.c
clang: error: -lm: 'linker' input unused [-Werror,-Wunused-command-line-argument]
make: *** [filereader.o] Error 1
```

**Comment by Soneji** [comment]
I was looking at the wfc component not the midi component, my bad. LGTM :)

**Comment by Soneji** [comment]
While you're here you could also add a `.gitignore`

**Comment by Soneji** [comment]
@noor-gate any chance of merge?

**Pull request merged**
